backend:
  name: git-gateway
  # repo: paulrobertpine/gatsby-dag
  branch: master

media_folder: static/assets

collections:
  - name: 'song'
    label: 'Song'
    folder: 'songs'
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'title', label: 'Title' }
      - { name: 'artist', label: 'Artist' }
      - { name: 'key', label: 'Key' }
      - { name: "chordpro", label: "ChordPro?", widget: "boolean", default: true }
      - { name: 'youtube', label: 'YouTube', widget: 'text' }
      - { name: 'body', label: 'Body', widget: 'markdown' }