backend:
  name: github
  repo: paulrobertpine/gatsby-dag
  branch: master

media_folder: static/assets

collections:
  - name: song
    label: Song
    # folder: songs
    create: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "artist", label: "Artist" }
      - { name: "key", label: "Key" }
      - { name: "body", label: "Body", widget: "markdown"}